<a href="https://colab.research.google.com/github/JimmyDela/UTEC_Fundamentos_programacion_python_2023/blob/main/Modulo_2/3.%20Numpy%20I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >

<h1 align=center><font size = 5> Numpy - Parte I
</font></h1>

---

## Tabla de Contenidos

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
    
1. <a href="#item31">Trabajando con arrays </a>
2. <a href="#item31">Algebra Matricial con arrays</a>  

</font>
</div>

---

# 1. Trabajando con Arrays 

In [1]:
#importando numpy
import numpy as np

In [ ]:
np.array(["j","p"])

array(['j', 'p'], dtype='<U1')

In [ ]:
## Generando error 
np.array([12,34,5,67,7,89],
         [2 ,3 ,5,6,7,8,8])

TypeError: ignored

In [ ]:
a= np.array([[12,34,5,67,7,89],
             [12,23,5,67,7,88]])
a.shape

(2, 6)

In [ ]:
a= np.array([[[12,34,5,67,7,89],
             [12,23,5,67,7,88],
             [12,23,5,67,7,88]],
            
             [[12,34,5,67,7,89],
             [12,23,5,67,7,88],
             [12,23,5,67,7,88]]])
a.shape

(2, 3, 6)

In [2]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)
type(a1)

[1 2 3]


numpy.ndarray

In [3]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [4]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Otras formas de crear arrays

In [25]:
np.zeros((3,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [26]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [27]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [31]:
np.linspace(1, 9, 3) ## se fefine un rango y la cantidad de datos equidistantes al rango

array([1., 5., 9.])

In [32]:
np.random.random((2, 2)) 

array([[0.1298949 , 0.84622792],
       [0.40494776, 0.35041446]])

In [47]:
np.array([np.random.randint(100) for x in range(0,4)])

array([90, 96, 66, 37])

### Atributos de un array

In [57]:
#Devuelve el número de dimensiones del array
my_array = np.identity(7)
my_array.ndim 

2

In [58]:
my_array.shape

(7, 7)

In [ ]:
#Devuelve una tupla con las dimensiones del array
my.shape

In [ ]:
#Devuelve el número de elementos del array
a.size

In [ ]:
#Devuelve el tipo de datos de los elementos del array
a.dtype

### Acceder a elementos del array

In [60]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a[1, 0])

4


In [63]:
## Cual sera la forma de extraer el valor 3 del array
print(a[0,2])
## Cual sera la forma de extraer el valor 3 del array
print(a[1,2])

3
6


In [66]:
a= np.array([[[12,34,5,67,7,89],
             [122,23,5,67,7,88],
             [132,23,5,67,7,88]],
            
             [[142,34,5,67,7,89],
             [172,23,5,67,7,88],
             [120,23,5,67,7,88]]])
print(a[1,0,0])
print(a[1][2][0])

142
120


In [ ]:
print(a[1][0])

In [ ]:
print(a[:, 0:2])

In [69]:
a = np.array([1, 2, 3,4,5])
a[2:]

array([3, 4, 5])

In [70]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a[1,1:]

array([5, 6])

In [71]:
a= np.array([[[12,34,5,67,7,89],
             [122,23,5,67,7,88],
             [132,23,5,67,7,88]],
            
             [[142,34,5,67,7,89],
             [172,23,5,67,7,88],
             [120,23,5,67,7,88]]])
a[ : , 0,4:]

array([[[ 7, 89],
        [ 7, 88],
        [ 7, 88]],

       [[ 7, 89],
        [ 7, 88],
        [ 7, 88]]])

In [83]:
a = np.array([[1, 2, 3, 4, 5],
              [1, 2, 3, 7, 8],
              [10, 11, 30, 77, 18]])
a[1:,2:4]

array([[ 3,  7],
       [30, 77]])

### Filtrado de elementos de un array

In [89]:
a = np.array([[1, 2, 4],
              [4, 5, 6]])
m = a[(a % 2 == 0)] 
m.reshape(2,2)

array([[2, 4],
       [4, 6]])

In [ ]:
print(a[(a % 2 == 0) &  (a > 2)])

### Operaciones matemáticas con arrays

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

In [ ]:
print(a + b )

In [ ]:
print(a / b)

In [ ]:
print(a ** 2)

# 2. Álgebra matricial con arrays

### Producto escalar de dos vectores

u.dot(v): Devuelve el producto escalar de los vectores u y v.



In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])
print(a @ b)

In [ ]:
print(a.dot(b))

In [ ]:
a*b

### Módulo de un vector

norm(v): Devuelve el módulo del vector v.

In [ ]:
a = np.array([3, 4])

In [ ]:
print(np.linalg.norm(a))

### Producto de dos matrices

a.dot(b) : Devuelve el producto matricial de las matrices a y b siempre y cuando sus dimensiones sean compatibles.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)

In [ ]:
print(a.dot(b))

### Matriz traspuesta

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)

### Traza de una matriz

a.trace() : Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())

### Determinante de una matriz

det(a) : Devuelve el determinante de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

### Matriz inversa

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

### Autovalores de una matriz


eigvals(a) : Devuelve los autovalores de la matriz cuadrada a.



In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))

### Autovectores de una matriz

eig(a) : Devuelve los autovalores y los autovectores asociados de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eig(a))

solve(a, b) : Devuelve la solución del sistema de ecuaciones lineales con los coeficientes de la matriz a y los términos independientes de la matriz b.

In [ ]:
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2 
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))


In [93]:
ciudad_1={'nombre':'Lima',
          'Pais':'Perú',
          'población':'10 MM',
          'Hecho':'Tiene el mejor ceviche y está en el mercado el Eden', 
          }
ciudad_2={'nombre':'La Paz',
          'Pais':'Bolivia',
          'población':'1 MM',
          'Hecho':'Tiene la mejor salteña y es la Ortis', 
          }
ciudad_3={'nombre':'Santa Cruz',
          'Pais':'Bolivia',
          'población':'3 MM',
          'Hecho':'Tiene el mejor arroz con queso y esta en la casa del Camba', 
          }
Ciudades=[ciudad_1,ciudad_2,ciudad_3]
for ciudad in Ciudades:
  print(ciudad.get("nombre"), "pertenece a la ciudad de :" ,ciudad.get("Pais"))

Lima pertenece a la ciudad de : Perú
La Paz pertenece a la ciudad de : Bolivia
Santa Cruz pertenece a la ciudad de : Bolivia


### Solución de un sistema de ecuaciones

---

# Gracias por completar este laboratorio!

---
